services:
    mosdns:
        container_name: mosdns
        restart: unless-stopped
        network_mode: host
        # ports:
           # - 53:53/udp
           # - 53:53/tcp
           # - 15011:9080  # API
        volumes:
            - ./mosdns:/etc/mosdns   # 运行所需配置文件路径，非二进制文件路径，
        image: irinesistiana/mosdns:v4.5.3

        # 替换二进制文件命令 #
        # 将二进制文件上传至宿主任意目录下，例如(/mnt/docker/mosdns-tmp/),然后宿主机执行
        # 赋可执行权限
        # chmod +x /mnt/docker/mosdns-tmp/mosdns
        # 拷贝到容器内二进制运行路径
        # docker cp /mnt/docker/mosdns-tmp/mosdns mosdns:/usr/bin/mosdns
        # 验证容器内二进制可执行权限
        # docker exec mosdns ls -l /usr/bin/mosdns
        # 验证容器内二进制版本
        # docker exec mosdns mosdns version
        # 若无可执行权限，执行一下命令
        # docker exec mosdns chmod +x /usr/bin/mosdns
        # 或者进入容器
        # docker exec -it mosdns sh
        # 容器内执行
        # ls -l /usr/bin/mosdns
        # chmod +x /usr/bin/mosdns

    prometheus:
        container_name: prometheus
        restart: unless-stopped
        networks:
          - grafana-dashboard-network
        ports:
            # 将端口暴露给便于webUI查询数据
            - 15012:9090
        volumes:
            - ./grafana-dashboard/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        image: prom/prometheus:v3.0.0

    loki:
        container_name: loki
        volumes:
            - ./grafana-dashboard/loki:/loki
        networks:
          - grafana-dashboard-network
        ports:
            # 将端口暴露给vector推送使用
            - 15013:3100
        image: grafana/loki:main-92a4dda
        command: -config.file=/loki/config.yaml

    vector:
        container_name: vector
        restart: unless-stopped
        networks:
          - grafana-dashboard-network
        volumes:
            - ./grafana-dashboard/vector:/etc/vector
            # 注意容器 外 路径需要与 mosdns日志文件plugin_info_log.log路径 一致
            # 注意容器 内 路径需要与 config.transforms.mosdns-input.condition.filename 一致
            - ./mosdns/plugin_info_log.log:/var/log/plugin_info_log.log
        image: timberio/vector:nightly-2026-03-03-alpine
        command: ["--config", "/etc/vector/config.yaml"] 

    grafana: 
        container_name: grafana
        restart: unless-stopped
        networks:
          - grafana-dashboard-network
        ports:
            # webUI端口
            - 15014:3000
        volumes:
            - ./grafana-dashboard/grafana:/var/lib/grafana
        image: grafana/grafana-image-tags:13.0.0-22707891732-amd64

networks:
    grafana-dashboard-network:
        driver: bridge 