{
 "title": "MosDNS-X 监控",
 "tags": [
  "mosdns",
  "v4",
  "mosdns-x"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "DNS 总查询数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(mosdns_plugin_global_metrics_query_total{job=\"mosdns\"}[$__range])))"
    }
   ]
  },
  {
   "title": "查询错误总数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(mosdns_plugin_global_metrics_err_total{job=\"mosdns\"}[$__range])))"
    }
   ]
  },
  {
   "title": "DNS 总平均响应延时",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "delta(mosdns_plugin_global_metrics_response_latency_millisecond_sum{job=\"mosdns\"}[$__range])/delta(mosdns_plugin_global_metrics_response_latency_millisecond_count{job=\"mosdns\"}[$__range])"
    }
   ]
  },
  {
   "title": "DNS 响应延迟区间",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "ceil(increase(mosdns_plugin_global_metrics_response_latency_millisecond_bucket{le!=\"+Inf\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "当前 Cache 条目数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"mosdns_plugin_cache_.*_cache_size\",job=\"mosdns\"})"
    }
   ]
  },
  {
   "title": "总 Cache 命中率",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(instance) (count_over_time({app=\"mosdns\", logger=\"log_query_cache_hit\"} | json [$__range])) / sum by(instance) (count_over_time({app=\"mosdns\", logger=\"log_query_start\"} | json [$__range]))"
    }
   ]
  },
  {
   "title": "DNS P95 响应延时",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, instance, job) (rate(mosdns_plugin_global_metrics_response_latency_millisecond_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "查询明细",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "查询域名TOP 20",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(20, sum by(domain) (count_over_time({app=\"mosdns\", logger=\"log_query_start\"} | json | domain != `` [$__range])))"
      }
     ]
    },
    {
     "title": "客户端查询TOP 20",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(20, sum by(client_ip) (count_over_time({app=\"mosdns\", logger=\"log_query_start\"} | json | client_ip != `` [$__range])))"
      }
     ]
    },
    {
     "title": "命中缓存TOP 20",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(20, sum by(domain) (count_over_time({app=\"mosdns\", logger=\"log_query_cache_hit\"} | json | domain != `` [$__range])))"
      }
     ]
    },
    {
     "title": "本地查询TOP 20",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(20, sum by(domain) (count_over_time({app=\"mosdns\", logger=\"log_query_is_local_resolve\"} | json | domain != `` [$__range])))"
      }
     ]
    },
    {
     "title": "远程查询TOP 20",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(20, sum by(domain) (count_over_time({app=\"mosdns\", logger=\"log_query_is_remote_resolve\"} | json | domain != `` [$__range])))"
      }
     ]
    },
    {
     "title": "拦截域名TOP 20",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(20, sum by(domain) (count_over_time({app=\"mosdns\", logger=\"log_query_is_ad\"} | json | domain != `` [$__range])))"
      }
     ]
    }
   ]
  },
  { "title": "应答明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "DNS查询应答",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"mosdns\", logger!=\"log_query_start\"}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS (总查询)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 429 },
     "targets": [
      {
       "expr": "sum by(instance) (rate(mosdns_plugin_cache_lan_query_total[$__rate_interval]) + rate(mosdns_plugin_cache_wan_query_total[$__rate_interval]) + rate(mosdns_plugin__default_cache_query_total[$__rate_interval]))"
      }
     ]
    }
   ]
  }
 ]
}